### ISSUE TITLE
PyAI: Crash with certain script ID's

### ISSUE THREAD

**Issue by poiuyqwert** [poiuyqwert/PyMS#108]
[Source](http://www.staredit.net/369737/)

**Comment by Pr0nogo** [comment]
Attempting to save with any nonstandard script ID will result in this:

> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "C:\Users\prono\Desktop\Libraries\Tools\SCBW\PyMS-aise\PyAI.pyw", line 2854, in saveas
    if self.save(ai=aiscript, bw=bwscript):
  File "C:\Users\prono\Desktop\Libraries\Tools\SCBW\PyMS-aise\PyAI.pyw", line 2835, in save
    self.ai.compile(ai, bw)
  File "C:\Users\prono\Desktop\Libraries\Tools\SCBW\PyMS-aise\Libs\AIBIN.py", line 2774, in compile
    table += struct.pack('<4s3L', id, offset, string+1, flags)
error: argument for 's' must be a string

Example of nonstandard script ID: https://i.imgur.com/TYj5Frn.png
